import { Toaster } from "sonner";
import "../styles/globals.css";
import "animate.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        {children}
        <Toaster richColors theme="dark" />
      </body>
    </html>
  );
}
